# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bqmodel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbqmodel.proto\"\x80\x02\n\x05Tweet\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x19\n\x11\x63reated_timestamp\x18\x04 \x01(\x03\x12\x0f\n\x07user_id\x18\x05 \x01(\t\x12\x16\n\x0eretweets_count\x18\x06 \x01(\x05\x12\x1a\n\x12quote_tweets_count\x18\x07 \x01(\x05\x12\x13\n\x0blikes_count\x18\x08 \x01(\x05\x12\x10\n\x08hashtags\x18\t \x03(\t\x12\x0f\n\x07replies\x18\n \x03(\t\x12\x14\n\x0csource_label\x18\x0b \x01(\t\x12\x0e\n\x06\x65ntity\x18\x0c \x01(\t\x12\x0f\n\x07\x64\x61ta_ts\x18\r \x01(\x03\"\x90\x02\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x19\n\x11\x63reated_timestamp\x18\x05 \x01(\x03\x12\x10\n\x08verified\x18\x06 \x01(\x08\x12\x10\n\x08location\x18\x07 \x01(\t\x12\x17\n\x0f\x66ollowers_count\x18\x08 \x01(\x05\x12\x15\n\rfriends_count\x18\t \x01(\x05\x12\x16\n\x0estatuses_count\x18\n \x01(\x05\x12\x18\n\x10\x66\x61vourites_count\x18\x0b \x01(\x05\x12\r\n\x05label\x18\x0c \x01(\t\x12\x0f\n\x07\x64\x61ta_ts\x18\r \x01(\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bqmodel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TWEET._serialized_start=18
  _TWEET._serialized_end=274
  _USER._serialized_start=277
  _USER._serialized_end=549
# @@protoc_insertion_point(module_scope)
